### ISSUE TITLE
AttributeError: module 'o365spray' has no attribute '__version__'

### ISSUE THREAD

**Issue by fsacer** [0xZDH/o365spray#15]
Installing with Python 3.9.2, pipx 1.1.0 and pip 20.3.4 results in the error message `AttributeError: module 'o365spray' has no attribute '__version__'`, additionally the `SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.` warning is displayed.

Used command `pipx install git+https://github.com/0xZDH/o365spray`.

**Comment by 0xZDH** [comment]
It seems there is an issue with importing `o365spray.__version__` during the build process during the pipx installation - so the fix appears to be shifting the version attribute in the setup.cfg file to: `o365spray.__init__.__version__`.

I have updated the setup.cfg file in the `dev` branch which you can install via pipx using:
`pipx install git+https://github.com/0xZDH/o365spray@dev`

I will update the main branch once I can confirm this change doesn't break anything else - until then, if you would like to use the main branch you can clone the repo and update like 3 of setup.cfg to be: `version = attr: o365spray.__init__.__version__` -- then install via: `pipx install .`

**Comment by fsacer** [comment]
Thanks for the prompt and detailed reply. 👍
