### ISSUE TITLE
Problems with running Domain Validation

### ISSUE THREAD

**Issue by KingAD2012** [0xZDH/o365spray#20]
Whenever I am trying to start a spray it says that the Domains are not using O365 although they are provided in the Description as working. I then tried to validate them manually and the following error came up:

 root@UnknownPC:~/o365spray# python3 o365spray -v -d portal.office.com
/usr/bin/python3: can't find '__main__' module in '/root/o365spray/o365spray'

When running the spray command I get this error:

root@UnknownPC:~/o365spray# python3 o365spray.py --spray -U names.txt -P 10-million-password-list-top-1000000.txt -c 5 -d https://outlook.office365.com/

            *** O365 Spray ***

>----------------------------------------<

   > version        :  1.3.7
   > domain         :  https://outlook.office365.com/
   > spray          :  True
   > userfile       :  names.txt
   > passfile       :  10-million-password-list-top-1000000.txt
   > count          :  5 passwords/spray
   > lockout        :  15.0 minutes
   > validate_type  :  getuserrealm
   > spray_type     :  activesync
   > rate           :  10 threads
   > safe           :  10 locked accounts
   > timeout        :  25 seconds
   > output         :  .
   > start          :  2023-05-27 00:49:30

>----------------------------------------<

[*] Performing O365 validation for: https://outlook.office365.com/

[FAILED]        The following domain is not using O365: https://outlook.office365.com/

I am running Ubuntu as WLS on my Windows 11 PC and have python 3 as well as o365spray installed. 
Thanks for any help!

**Comment by 0xZDH** [comment]
Based on your output provided, it appears you are running `version : 1.3.7`. The latest version available is `3.0.2`. Please update your local copy of the tool to the latest available version and try again.

If you are still running into the same issues, reopen this issue with further details.
