### ISSUE TITLE
Safe/lockout is not used when using a paired list

### ISSUE THREAD

**Issue by JJK96** [0xZDH/o365spray#7]
In the code:

```
        if args.paired:
            logging.info("Password spraying using paired usernames:passwords.")

            loop.run_until_complete(spray.run(passlist))
            # Note: Since we are pairing usernames and passwords, we can ignore the
            #       lockout reset wait call as we should only be running a single
            #       cycle

```

The note is not true in all cases, if the paired list contains multiple passwords for the same user, the lockout policy should still be used. e.g.

```
alice:qwerty
bob:password123
bob:bobisthebest
```

**Comment by 0xZDH** [comment]
That comment is specifically meant for that section in `__main__.py` as we will only cycle through the passed credentials a single time instead of looping like we do with a password set. The lockout handling is still observed and handled (when applicable) by the sprayer handler itself as you can see for example here:
https://github.com/0xZDH/o365spray/blob/master/o365spray/core/handlers/sprayer.py#L295

**Comment by JJK96** [comment]
Still, the count parameter is not used when the `--paired` option is used. The help text shows the following:

```
 -c COUNT, --count COUNT
                        Number of password attempts to run per user before resetting the lockout account
                        timer. Default: 1
```

I take this to mean that it will do one password per user and then wait for the lockout timer (15 min in my case). However, when I run the attack with `--paired` on a dataset like the above example. It will happily execute all the guesses for bob in a single run, thereby possibly locking out the account for bob. I've looked a bit in the code, but a fix for this is not trivial I think.

**Comment by 0xZDH** [comment]
Ah okay - I now understand what you are referring to. Yes, the way the code is built is if a `--paired` file is passed the tool is somewhat 'dumb' and assumes that it's a single password attempt for each user (when I originally wrote this handling I seem to have ignored the idea of duplicate users with different passwords...). I will look into a solution for handling this and try to get something pushed up to a dev-branch for testing.

**Comment by 0xZDH** [comment]
I have pushed some changes/fixes (v2.0.4) to the `paired-updates` branch that should resolve this issue. Once I stress test the updates a bit more I will get them merged into the master branch

**Comment by JJK96** [comment]
Thank you for working on this!

**Comment by kluo84** [comment]
Hello, anyway to get out the Account locked when we do the password spraying? I tried --safe 3 --sleep 30 with 1 password, but the accounts are still locked.

**Comment by 0xZDH** [comment]
Paired updates have been written into the dev branch with several other fixes/updates. Once things have been tested a bit more it will be merged into the master branch.
